"""Generate GROMACS .mdp (run-parameter) files from config/md.yaml.

Every simulation stage is described by a `Stage`; `render_mdp` turns a stage
plus the md settings into mdp text. All mdp files in the project come from
here, so a setting changed in md.yaml changes it everywhere at once.

Stage sequence for every run:
    em      energy minimization: removes bad contacts from building the box
    eq1..   equilibration: restraints hold lipids/aggregate in place while the
            water and ions relax, then are weakened stage by stage
    prod    production: no restraints, this is the data we analyze
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .config import Config, ConfigError

SMOKE_STEPS = 1000


@dataclass
class Stage:
    name: str
    kind: str                      # em | nvt | npt | prod
    nsteps: int
    restraints: dict = field(default_factory=dict)
    gen_vel: bool = False          # first dynamics stage draws random velocities

    @property
    def mdp_name(self) -> str:
        return f"{self.name}.mdp"


# ---------------------------------------------------------------------------
# CHARMM36 nonbonded settings. HARDCODED ON PURPOSE -- do not move to config.
#
# CHARMM36 lipid parameters were fit together with this exact treatment of
# long-range interactions. Change it (e.g. plain cutoff, potential-shift, a
# different rvdw, or dispersion correction on) and the membrane silently
# comes out wrong: area per lipid and order parameters drift away from
# experiment, with no error message. References: Klauda et al. 2010 (J Phys
# Chem B 114:7830); the CHARMM36 port notes for GROMACS; CHARMM-GUI output.
# ---------------------------------------------------------------------------
CHARMM36_NONBONDED = """\
; ---- Nonbonded interactions: CHARMM36 REQUIRES exactly this. Do not edit. ----
cutoff-scheme           = Verlet        ; modern GROMACS neighbour searching
nstlist                 = 20            ; neighbour list update interval (Verlet buffer is automatic)
coulombtype             = PME           ; particle-mesh Ewald: full long-range electrostatics
rcoulomb                = 1.2           ; nm, real-space electrostatics cutoff
vdwtype                 = Cut-off
vdw-modifier            = Force-switch  ; LJ force smoothly switched to zero ...
rvdw-switch             = 1.0           ; ... starting at 1.0 nm ...
rvdw                    = 1.2           ; ... reaching zero at 1.2 nm
DispCorr                = no            ; CHARMM36 lipids were fit WITHOUT long-range dispersion correction
"""


def _steps(ps: float, dt: float) -> int:
    n = round(ps / dt)
    if n < 1 or abs(n * dt - ps) > 1e-6:
        raise ConfigError(f"{ps} ps is not a whole number of {dt} ps timesteps")
    return n


def stages(cfg: Config, smoke: bool = False) -> list[Stage]:
    md = cfg.md
    dt = float(md["timestep_ps"])
    out = [Stage("em", "em", SMOKE_STEPS if smoke else 50000,
                 dict(cfg.require("md.minimization.restraints")))]
    eq = cfg.require("md.equilibration")
    for i, st in enumerate(eq):
        if st.get("ensemble") not in ("nvt", "npt"):
            raise ConfigError(f"equilibration stage {st.get('name')}: ensemble must be nvt or npt")
        for k in ("lipid_pos", "lipid_dih", "aggregate_pos"):
            if st.get("restraints", {}).get(k) is None:
                raise ConfigError(f"equilibration stage {st['name']}: restraints.{k} is null")
        n = SMOKE_STEPS if smoke else _steps(float(cfg.require("md.equilibration")[i]["length_ps"]), dt)
        out.append(Stage(st["name"], st["ensemble"], n, dict(st["restraints"]), gen_vel=(i == 0)))
    n = SMOKE_STEPS if smoke else _steps(float(cfg.require("md.production.length_ns")) * 1000, dt)
    out.append(Stage("prod", "prod", n, {}))
    return out


def _defines(md: dict, restraints: dict) -> str:
    rm = md["restraint_macros"]
    parts = []
    for key, switch, fc in (("lipid_pos", "lipid_pos_switch", "lipid_pos_fc"),
                            ("lipid_dih", "lipid_dih_switch", "lipid_dih_fc"),
                            ("aggregate_pos", "aggregate_pos_switch", "aggregate_pos_fc")):
        value = float(restraints.get(key) or 0.0)
        if value > 0:
            parts += [f"-D{rm[switch]}", f"-D{rm[fc]}={value:g}"]
    return " ".join(parts)


def render_mdp(cfg: Config, stage: Stage, gen_seed: int, temperature_K: float | None = None,
               smoke: bool = False) -> str:
    md = cfg.md
    T = float(temperature_K if temperature_K is not None else md["temperature_K"])
    dt = float(md["timestep_ps"])
    head = [f"; {stage.name}.mdp -- generated by lipidmd.mdp from config/md.yaml. DO NOT EDIT.",
            "; Regenerate with: python scripts/make_mdp.py"]
    if smoke:
        head.append("; *** SMOKE TEST SETTINGS -- NOT FOR PRODUCTION ***")
    define = _defines(md, stage.restraints)
    head.append(f"define                  = {define}   ; restraints on for this stage (empty = none)")

    if stage.kind == "em":
        body = [
            "; ---- Energy minimization ----",
            "integrator              = steep     ; steepest descent: robust for removing clashes",
            f"nsteps                  = {stage.nsteps}",
            "emtol                   = 1000.0    ; kJ/mol/nm: stop when max force is below this",
            "emstep                  = 0.01      ; nm, initial step size",
        ]
        return "\n".join(head + body + ["", CHARMM36_NONBONDED, _constraints(em=True), "pbc = xyz", ""])

    groups = cfg.require("md.coupling_groups")
    n_g = len(groups)
    def every(key: str) -> int:
        return _steps(float(cfg.require(f"md.output.{key}")), dt)
    nxtc, nene, nlog = every("xtc_interval_ps"), every("energy_interval_ps"), every("log_interval_ps")
    ncalc = 100 if nene % 100 == 0 else nene

    body = [
        "; ---- Integration ----",
        "integrator              = md        ; leap-frog",
        f"dt                      = {dt}     ; ps (2 fs is safe because H bonds are constrained)",
        f"nsteps                  = {stage.nsteps}   ; = {stage.nsteps * dt:g} ps",
        "",
        "; ---- Output ----",
        f"nstxout-compressed      = {nxtc}   ; coordinates to .xtc every {nxtc * dt:g} ps",
        "nstxout                 = 0         ; no full-precision trajectory (huge files)",
        "nstvout                 = 0",
        "nstfout                 = 0",
        f"nstenergy               = {nene}   ; energies to .edr every {nene * dt:g} ps",
        f"nstlog                  = {nlog}   ; log every {nlog * dt:g} ps",
        f"nstcalcenergy           = {ncalc}",
        "",
        CHARMM36_NONBONDED,
        _constraints(em=False),
        "; ---- Temperature coupling ----",
        f"tcoupl                  = {cfg.require('md.thermostat')}",
        f"tc-grps                 = {' '.join(groups)}   ; groups from index.ndx, coupled separately",
        f"tau-t                   = {' '.join([str(cfg.require('md.tau_t_ps'))] * n_g)}",
        f"ref-t                   = {' '.join([f'{T:g}'] * n_g)}",
        "",
        "; ---- Centre-of-mass motion removal (stops the whole box drifting) ----",
        "comm-mode               = Linear",
        f"comm-grps               = {' '.join(groups)}",
        "",
    ]
    if stage.kind == "nvt":
        body += ["; ---- Pressure coupling: none (constant volume) ----", "pcoupl                  = no", ""]
    else:
        baro = cfg.require("md.barostat_production" if stage.kind == "prod" else "md.barostat_equilibration")
        comp = cfg.require("md.compressibility_per_bar")
        P = float(md["pressure_bar"])
        body += [
            "; ---- Pressure coupling ----",
            f"pcoupl                  = {baro}",
            f"pcoupltype              = {md['pressure_coupling_type']}  ; membrane plane (xy) and normal (z) scale independently",
            f"tau-p                   = {cfg.require('md.tau_p_ps')}",
            f"ref-p                   = {P:g} {P:g}   ; bar, xy then z",
            f"compressibility         = {comp:g} {comp:g}   ; 1/bar, xy then z",
            "refcoord-scaling        = com       ; required when position restraints meet pressure coupling",
            "",
        ]
    if stage.gen_vel:
        body += [
            "; ---- Starting velocities: drawn at random (seeded per replica) ----",
            "gen-vel                 = yes",
            f"gen-temp                = {T:g}",
            f"gen-seed                = {gen_seed}   ; replicas differ by this seed",
            "continuation            = no",
        ]
    else:
        body += [
            "; ---- Continue from the previous stage's velocities ----",
            "gen-vel                 = no",
            "continuation            = yes       ; don't re-constrain the starting structure",
        ]
    body.append("pbc                     = xyz")
    return "\n".join(head + body) + "\n"


def _constraints(em: bool) -> str:
    return (
        "; ---- Bond constraints ----\n"
        "constraints             = h-bonds   ; bonds to hydrogen held rigid -> allows a 2 fs step\n"
        "constraint-algorithm    = LINCS\n"
        + ("" if em else "lincs-order             = 4\n")
    )


def write_all(cfg: Config, out_dir: Path, gen_seed: int, smoke: bool = False,
              temperature_K: float | None = None) -> list[Stage]:
    out_dir.mkdir(parents=True, exist_ok=True)
    sts = stages(cfg, smoke=smoke)
    for st in sts:
        (out_dir / st.mdp_name).write_text(render_mdp(cfg, st, gen_seed, temperature_K, smoke))
    return sts


ION_MDP = """; minimal parameters only used to make a .tpr for gmx genion (no dynamics run)
integrator = steep
nsteps     = 0
cutoff-scheme = Verlet
coulombtype = PME
rcoulomb   = 1.2
vdwtype    = Cut-off
vdw-modifier = Force-switch
rvdw-switch = 1.0
rvdw       = 1.2
"""
