"""SLURM job scripts, checkpoint-restart chaining, submission, and status.

How a run proceeds on the cluster
---------------------------------
Each run directory (runs/<system>/rep<N>/) gets one job script, job.sh. When
it starts it walks through the stages in order (em, eq1, eq2, ..., prod):

    * a stage whose <stage>.done marker exists is skipped;
    * otherwise grompp makes <stage>.tpr (once), and mdrun runs it with
      `-cpi <stage>.cpt`, i.e. "continue from the checkpoint if there is one";
    * mdrun gets `-maxh`: a few minutes before the SLURM wall-clock limit it
      writes a checkpoint and exits cleanly;
    * if a stage stopped because of -maxh, the script resubmits ITSELF and
      exits. The next job picks up from the .cpt file. A 500 ns run is
      therefore a chain of jobs, each continuing exactly where the last one
      stopped (checkpoints store positions, velocities, thermostat state and
      random-number state, so the continuation is seamless).

Small state files in the run directory drive `status`:
    .state     QUEUED | RUNNING | DONE | FAILED
    .jobid     most recent SLURM job ID
    .segments  number of job submissions so far
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .config import Config, ConfigError, RunSpec
from .mdp import Stage

# Messages GROMACS prints when mdrun stops early because of -maxh or a
# signal (SLURM sends SIGTERM shortly before killing a job).
EARLY_STOP_PATTERNS = ["will terminate the run", "Received the TERM signal", "Received the INT signal",
                       "Received the USR1 signal"]


def walltime_hours(walltime: str) -> float:
    """'HH:MM:SS' or 'D-HH:MM:SS' -> hours."""
    days = 0
    if "-" in walltime:
        d, walltime = walltime.split("-", 1)
        days = int(d)
    parts = [int(x) for x in walltime.split(":")]
    while len(parts) < 3:
        parts.insert(0, 0)
    h, m, s = parts
    return days * 24 + h + m / 60 + s / 3600


def _hpc(cfg: Config, key: str, placeholder: bool) -> str:
    v = cfg.hpc.get(key)
    if v is None:
        if placeholder:
            return f"TODO_{key.upper()}"
        raise ConfigError(f"hpc.yaml: '{key}' is not set -- needed to submit jobs")
    return str(v)


def render_job_script(cfg: Config, run_dir: Path, job_name: str, stage_list: list[Stage],
                      placeholders: bool = False) -> str:
    """The SLURM script for one run. `placeholders=True` (dry run) fills unset
    HPC values with TODO_... instead of failing."""
    h = cfg.hpc
    wall = _hpc(cfg, "walltime", placeholders)
    try:
        maxh = max(walltime_hours(wall) - float(h["safety_margin_min"]) / 60, 0.1)
    except ValueError:
        maxh = 0.1  # placeholder walltime
    gpu = f"gpu:{h['gpu_type']}:{h['gpus_per_job']}" if h.get("gpu_type") else f"gpu:{h['gpus_per_job']}"
    sb = [
        "#!/bin/bash",
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --partition={_hpc(cfg, 'partition', placeholders)}",
        f"#SBATCH --gres={gpu}",
        f"#SBATCH --cpus-per-task={_hpc(cfg, 'cpus_per_task', placeholders)}",
        f"#SBATCH --time={wall}",
        "#SBATCH --output=slurm-%j.out",
    ]
    if h.get("account"):
        sb.append(f"#SBATCH --account={h['account']}")
    if h.get("mem"):
        sb.append(f"#SBATCH --mem={h['mem']}")

    stages_bash = []
    prev = "start.gro"
    for st in stage_list:
        stages_bash.append(f'run_stage {st.name} {st.mdp_name} {prev} {"em" if st.kind == "em" else "md"}')
        prev = f"{st.name}.gro"

    modules = "\n".join(h.get("module_lines") or ["# (no module lines configured in hpc.yaml)"])
    patterns = " ".join(f'-e "{p}"' for p in EARLY_STOP_PATTERNS)
    return f"""{chr(10).join(sb)}
# -----------------------------------------------------------------------------
# Generated by lipidmd.run -- regenerate with scripts/run.py rather than editing.
# Run directory: {run_dir}
# -----------------------------------------------------------------------------
set -uo pipefail
cd "{run_dir}" || exit 1

{modules}

GMX="{h.get('gmx', 'gmx')}"
MAXH={maxh:.3f}            # stop mdrun this many hours in, leaving time to checkpoint
MAX_SEGMENTS={h['max_segments']}
export OMP_NUM_THREADS=${{SLURM_CPUS_PER_TASK:-1}}

echo "${{SLURM_JOB_ID:-local}}" > .jobid
echo RUNNING > .state
seg=$(( $(cat .segments 2>/dev/null || echo 0) + 1 )); echo $seg > .segments
if (( seg > MAX_SEGMENTS )); then
    echo "Exceeded MAX_SEGMENTS=$MAX_SEGMENTS resubmissions" | tee -a .failure
    echo FAILED > .state; exit 1
fi

fail() {{ echo "$(date): $*" | tee -a .failure; echo FAILED > .state; exit 1; }}

resubmit() {{
    # Hit the wall-clock limit: queue the next segment, which continues from the checkpoint.
    jid=$(sbatch --parsable "{run_dir}/job.sh") || fail "resubmission failed"
    echo "$jid" > .jobid; echo QUEUED > .state
    echo "$(date): segment $seg stopped at -maxh; resubmitted as job $jid"
    exit 0
}}

# run_stage NAME MDP INPUT_GRO KIND
run_stage() {{
    local name=$1 mdp=$2 input=$3 kind=$4
    [[ -f $name.done ]] && return 0
    echo "$(date): stage $name"
    if [[ ! -f $name.tpr ]]; then
        # grompp = GROMACS preprocessor: combines mdp + coordinates + topology into a .tpr.
        # -r: reference positions for restraints (always the built structure, so restraints
        #     hold atoms where they started rather than drifting stage to stage).
        # -maxwarn 0: never ignore warnings.
        local tin=""; [[ $kind == md && -f ${{input%.gro}}.cpt ]] && tin="-t ${{input%.gro}}.cpt"
        $GMX grompp -f mdp/$mdp -c $input -r start.gro -p topol.top -n index.ndx \\
            -o $name.tpr $tin -maxwarn 0 || fail "grompp failed for $name"
    fi
    local before=$(wc -l < $name.log 2>/dev/null || echo 0)
    if [[ $kind == em ]]; then
        $GMX mdrun -deffnm $name {h.get('mdrun_extra_flags', '')} || fail "mdrun failed for $name"
    else
        # -cpi: continue from checkpoint if present; -maxh: stop cleanly before the time limit.
        $GMX mdrun -deffnm $name -cpi $name.cpt -maxh $MAXH {h.get('mdrun_extra_flags', '')} \\
            || fail "mdrun failed for $name"
        if tail -n +$((before + 1)) $name.log | grep -q {patterns}; then
            resubmit
        fi
    fi
    [[ -f $name.gro ]] || fail "$name finished without writing $name.gro"
    touch $name.done
}}

{chr(10).join(stages_bash)}

# Make molecules whole and centre the membrane: what the analysis expects.
if [[ ! -f prod_centered.xtc ]]; then
    printf "MEMB\\nSystem\\n" | $GMX trjconv -s prod.tpr -f prod.xtc -n index.ndx \\
        -o prod_centered.xtc -pbc mol -center || fail "trjconv failed"
fi
echo DONE > .state
echo "$(date): all stages done"
"""


# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------
@dataclass
class RunStatus:
    name: str
    state: str          # not-built | built | QUEUED | RUNNING | DONE | FAILED | stalled
    stage: str
    sim_time_ns: float | None
    target_ns: float | None
    jobid: str | None

    def row(self) -> str:
        t = "-" if self.sim_time_ns is None else f"{self.sim_time_ns:8.2f}"
        tgt = "" if self.target_ns is None else f" / {self.target_ns:g}"
        return f"{self.name:22s} {self.state:9s} {self.stage:6s} {t}{tgt} ns  {self.jobid or ''}"


def last_log_time_ps(log: Path) -> float | None:
    """Simulated time of the last energy block in a GROMACS .log file.

    Energy blocks look like:
               Step           Time
             500000     1000.00000
    """
    if not log.exists():
        return None
    lines = log.read_text(errors="replace").splitlines()
    for i in range(len(lines) - 2, -1, -1):
        f = lines[i].split()
        if f == ["Step", "Time"]:
            try:
                return float(lines[i + 1].split()[1])
            except (IndexError, ValueError):
                continue
    return None


def _squeue_state(jobid: str) -> str | None:
    if not shutil.which("squeue"):
        return None
    proc = subprocess.run(["squeue", "-h", "-j", jobid, "-o", "%T"], capture_output=True, text=True)
    s = proc.stdout.strip()
    return s or None


def run_status(run_dir: Path, name: str, stage_names: list[str], target_ns: float | None) -> RunStatus:
    if not (run_dir / "start.gro").exists():
        return RunStatus(name, "not-built", "-", None, target_ns, None)
    state = (run_dir / ".state").read_text().strip() if (run_dir / ".state").exists() else "built"
    jobid = (run_dir / ".jobid").read_text().strip() if (run_dir / ".jobid").exists() else None
    current = next((s for s in stage_names if not (run_dir / f"{s}.done").exists()), "done")
    t = last_log_time_ps(run_dir / "prod.log")
    sim_ns = None if t is None else t / 1000
    if state in ("QUEUED", "RUNNING") and jobid:
        sq = _squeue_state(jobid)
        if sq in ("PENDING", "CONFIGURING"):
            state = "QUEUED"
        elif sq in ("RUNNING", "COMPLETING"):
            state = "RUNNING"
        elif sq is None and shutil.which("squeue"):
            # SLURM no longer knows the job, but it never marked itself DONE/FAILED/QUEUED:
            # killed by the scheduler (e.g. time limit hit before -maxh) or node failure.
            state = "stalled"
    return RunStatus(name, state, current, sim_ns, target_ns, jobid)


def submit(run_dir: Path) -> str:
    proc = subprocess.run(["sbatch", "--parsable", str(run_dir / "job.sh")], capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"sbatch failed for {run_dir}: {proc.stderr}")
    jid = proc.stdout.strip().split(";")[0]
    (run_dir / ".jobid").write_text(jid + "\n")
    (run_dir / ".state").write_text("QUEUED\n")
    return jid


def run_dir_for(cfg: Config, run: RunSpec, smoke: bool) -> Path:
    base = cfg.systems["smoke_runs_dir"] if smoke else cfg.systems["runs_dir"]
    return cfg.path(base) / run.system.name / f"rep{run.replica}"


def prepare_run_dir(cfg: Config, run_dir: Path, job_name: str, gen_seed: int, smoke: bool,
                    placeholders: bool, temperature_K: float | None = None) -> list[Stage]:
    """Write mdp/ files and job.sh into an already-built run directory."""
    from .mdp import write_all

    stage_list = write_all(cfg, run_dir / "mdp", gen_seed, smoke=smoke, temperature_K=temperature_K)
    job = run_dir / "job.sh"
    job.write_text(render_job_script(cfg, run_dir.resolve(), job_name, stage_list, placeholders))
    job.chmod(0o755)
    # remembered for `status`
    prod = stage_list[-1]
    (run_dir / ".stages").write_text(" ".join(s.name for s in stage_list) + "\n")
    (run_dir / ".target_ns").write_text(f"{prod.nsteps * float(cfg.md['timestep_ps']) / 1000:g}\n")
    return stage_list


def status_for_dir(run_dir: Path, name: str) -> RunStatus:
    stages = (run_dir / ".stages").read_text().split() if (run_dir / ".stages").exists() else ["prod"]
    target = float((run_dir / ".target_ns").read_text()) if (run_dir / ".target_ns").exists() else None
    return run_status(run_dir, name, stages, target)
